version: "3.8"

services:
  todo-api:
    ports:
      - "5000:80"     # HTTP API
      - "5001:5001"   # gRPC (HTTP/2)
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Postgres: "Host=postgres;Database=todo_db;Username=postgres;Password=postgres"
      Redis__Connection: "redis:6379"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__User: "guest"
      RabbitMq__Password: "guest"
